version: '2'

services:
  pi-cam:
    build: .
    privileged: true
    ports:
      - "80:80"
    labels:
      io.balena.features.extra-firmware: '1' 
      io.balena.features.sysfs: '1'  # Only needed for imx500 examples
